### ISSUE TITLE
Erro no calculo do impacto do preço

### ISSUE THREAD

**Issue by ZigotoCripto** [triadxyz/triad-protocol#28]
https://github.com/triadxyz/triad-protocol/blob/99377128795e2b4d1f564433a38e9da6b81ff615/programs/triad-protocol/src/instructions/trade/close_order.rs#L79

Das linhas 79 à 94 são calculados os preços impactos e consequentemente o novo preço.

No entanto o preço impacto calculado está subdimensionado. Ele está utilizando para calculo apenas a liquidez de um dos sentidos (hype ou Flop) enquanto o calculo do preço utiliza a liquidez total.

Como o preço é baseado na razão da liquidez_direcional(hype ou flop) / liquidez total 

Não basta apenas calcular o price impact apenas com a liquidez direcional.

Não manjo de Rust, mas trazendo pra linguagem de programação acredito que o price impact deveria ser assim.

new_Price = (liquidez_direcional - current_amount) / (liquidez_total - current_amount)
Price_impact_% = (Price - new_price)/Price
Vou anexar na tabela mostrando as diferenças

![image](https://github.com/user-attachments/assets/198ea021-d781-46cb-827f-23177c1fb520)

**Comment by aposentarem10** [comment]
Considere o segundo Hype_liquid como Flop_Liquid, esqueci de mudar o título

**Comment by dannpl** [comment]
Great, thank you for share this idea. 

Let's talk on discord
